name: Build And Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run The Unit Tests
      run: npm run test:unit
    - name: Display username
      run: echo 'rosty_d'
  run-ui-tests:
    needs: build-and-unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js 20x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Install PlaywrightBrowsers
      run: npx playwright install
    - name: Start The App
      run: npm run start &
    - name: Run The UI Tests
      run: npm run test:ui
